[20.944118500] 2018-12-31 15:30:58,345 - INFO - launcher: Starting sanity checks
[20.944118500] 2018-12-31 15:30:58,345 - INFO - launcher: Checking for Python 3.5+
[20.944118500] 2018-12-31 15:30:58,345 - INFO - launcher: Checking console encoding
[20.944118500] 2018-12-31 15:30:58,345 - INFO - launcher: Setting console encoding to UTF-8
[20.944118500] 2018-12-31 15:30:58,345 - INFO - launcher: Ensuring we're in the right environment
[21.942138672] 2018-12-31 15:30:58,346 - INFO - launcher: Adding local bins/ folder to path
[22.938966751] 2018-12-31 15:30:58,347 - INFO - launcher: Required checks passed.
[22.938966751] 2018-12-31 15:30:58,347 - INFO - launcher: Optional checks passed.
[22.938966751] 2018-12-31 15:30:58,347 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.7011256217956543] 2018-12-31 15:30:59,025 - WARNING - musicbot.config | In config.py::MainThread(5112), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.7021219730377197] 2018-12-31 15:30:59,026 - INFO - musicbot.config | In config.py::MainThread(5112), line 123 in run_checks: Using i18n: config/i18n/en.json
[0.7041180133819580] 2018-12-31 15:30:59,028 - DEBUG - musicbot.json | In json.py::MainThread(5112), line 8 in __init__: Init JSON obj with config/i18n/en.json
[0.8706939220428467] 2018-12-31 15:30:59,194 - DEBUG - musicbot.bot | In bot.py::MainThread(5112), line 227 in _setup_logging: Set logging level to INFO
[0.8706939220428467] 2018-12-31 15:30:59,194 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 84 in __init__: Starting MusicBot 1.9.7
[0.8716690540313721] 2018-12-31 15:30:59,195 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 90 in __init__: Loaded autoplaylist with 2531 entries
[7.6042087078094482] 2018-12-31 15:31:05,928 - DEBUG - musicbot.bot | In bot.py::MainThread(5112), line 1074 in on_ready: Connection established, ready to go.
[7.6042087078094482] 2018-12-31 15:31:05,928 - DEBUG - musicbot.bot | In bot.py::MainThread(5112), line 339 in _cache_app_info: Caching app info
[7.8550195693969727] 2018-12-31 15:31:06,179 - DEBUG - musicbot.bot | In bot.py::MainThread(5112), line 889 in _scheck_ensure_env: Ensuring data folders exist
[7.8550195693969727] 2018-12-31 15:31:06,179 - DEBUG - musicbot.bot | In bot.py::MainThread(5112), line 905 in _scheck_server_permissions: Checking server permissions
[7.8550195693969727] 2018-12-31 15:31:06,179 - DEBUG - musicbot.bot | In bot.py::MainThread(5112), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[7.8560178279876709] 2018-12-31 15:31:06,180 - DEBUG - musicbot.bot | In bot.py::MainThread(5112), line 913 in _scheck_configs: Validating config
[7.8560178279876709] 2018-12-31 15:31:06,180 - DEBUG - musicbot.config | In config.py::MainThread(5112), line 212 in async_validate: Validating options...
[7.8560178279876709] 2018-12-31 15:31:06,180 - DEBUG - musicbot.bot | In bot.py::MainThread(5112), line 916 in _scheck_configs: Validating permissions config
[7.8560178279876709] 2018-12-31 15:31:06,180 - DEBUG - musicbot.permissions | In permissions.py::MainThread(5112), line 64 in async_validate: Validating permissions...
[7.8560178279876709] 2018-12-31 15:31:06,180 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 1091 in on_ready: Connected: 528812717444956161/Kpop Paradise Music#1136
[7.8560178279876709] 2018-12-31 15:31:06,180 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 1099 in on_ready: Owner:     270155491340976128/Akira#0962

[7.8570139408111572] 2018-12-31 15:31:06,181 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 1102 in on_ready: Server List:
[7.8570139408111572] 2018-12-31 15:31:06,181 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 1105 in on_ready:  - cube nz
[7.8570139408111572] 2018-12-31 15:31:06,181 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 1105 in on_ready:  - Kpop Paradise
[7.8580126762390137] 2018-12-31 15:31:06,182 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 1151 in on_ready: Not bound to any text channels
[7.8580126762390137] 2018-12-31 15:31:06,182 - INFO - musicbot.bot | In bot.py::MainThread(5112), line 1167 in on_ready: Not autojoining any voice channels
